# Generated by Django 4.1.2 on 2023-04-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktransaction1',
            name='bookquantity_no',
        ),
    ]
