# Generated by Django 4.1.2 on 2023-04-05 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_booktransaction1_bookquantity_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('late_charge', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookname', to='app.booktransaction1')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentname', to='app.booktransaction1')),
                ('transaction_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='app.booktransaction1')),
            ],
        ),
    ]
