# Generated by Django 4.1.2 on 2023-04-05 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_book_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_return',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookname', to='app.book'),
        ),
        migrations.AlterField(
            model_name='book_return',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentname', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book_return',
            name='transaction_date',
            field=models.DateField(),
        ),
    ]
