# Generated by Django 4.1.2 on 2023-04-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_book_return_book_alter_book_return_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_return',
            old_name='transaction_date',
            new_name='late_return_date',
        ),
    ]
