# Generated by Django 4.1.2 on 2023-04-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_transaction_date_book_return_late_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_return',
            name='late_charge',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book_return',
            name='late_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
