# Generated by Django 4.1.2 on 2023-04-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_book_return_late_charge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_return',
            old_name='late_charge',
            new_name='late_charge_of_one_day',
        ),
    ]
