# Generated by Django 4.1.2 on 2023-04-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_late_charge_book_return_late_charge_of_one_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_return',
            old_name='late_charge_of_one_day',
            new_name='late_charge_rate',
        ),
    ]
