# Generated by Django 4.1.2 on 2023-04-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_late_charge_of_one_day_book_return_late_charge_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_return',
            name='late_charge_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
