# Generated by Django 4.1.2 on 2023-04-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_book_return_late_charge_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('Total_fee', models.IntegerField()),
            ],
        ),
    ]
