# Generated by Django 4.1.2 on 2023-04-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_course_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='duration',
            field=models.CharField(max_length=40),
        ),
    ]
