# Generated by Django 4.1.2 on 2023-04-06 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_course_details_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_fee', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentname', to='app.course_details')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student1_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
