# Generated by Django 4.1.2 on 2023-04-06 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_course_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentname', to='app.course_details'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pending_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='course_fee',
        ),
    ]
