# Generated by Django 4.1.2 on 2023-04-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_customuser_course_customuser_pending_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('0', 'admin'), ('1', 'student')], max_length=200),
        ),
    ]
