# Generated by Django 4.1.1 on 2023-04-07 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookquantity_no',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Custname', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
